### ISSUE TITLE
LibReport generate report file failed!!

### ISSUE THREAD

**Issue by aJIEw** [znyang/library-analysis#29]
执行 libReportReleaseCompileClasspath 报错：
LibReport generate report file failed!!! ERROR: Could not resolve all files for configuration ':app:releaseCompileClasspath'.

当我把依赖的 implementation 改为 compile 后再执行 libReportCompile 可以正常生成 text 和 html 文件。

运行环境：Android Studio 3.2 + Gradle 4.4

**Comment by znyang** [comment]
不好意思，有一段时间没更新了。。
可以把你有问题的依赖配置发出来吗？

感谢反馈

**Comment by aJIEw** [comment]
已经找到解决办法，发现只要把依赖的 module library 注释掉再跑 libReportReleaseCompileClasspath 就可以正常生成报告，如下：
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
//    implementation project(':RecorderModule')
//    implementation project(':MaterialTabsModule')
    implementation "com.android.support:multidex:$multidex_version"
    ...
}
p.s. 感谢提供这么好用的插件~

**Comment by znyang** [comment]
@aJIEw 问题已经在0.2.2中解决了，你再试下？

**Comment by aJIEw** [comment]
> @aJIEw 问题已经在0.2.2中解决了，你再试下？

Work like a charm
